name: products-api

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:5000
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - type: bind
        source: ./src
        target: /app/src
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 8080:5432
    env_file:
      - db.env
    restart: always
